# Generated by Django 3.2.4 on 2021-06-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='mainuser',
            name='github_auth_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
