# Generated by Django 3.2.4 on 2021-06-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210613_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainuser',
            old_name='github_auth_token',
            new_name='github_access_token',
        ),
    ]
